# Generated by Django 4.1.6 on 2023-02-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=15)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('img_full', models.ImageField(upload_to='telephones/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webstore.category')),
            ],
        ),
    ]
