# Generated by Django 4.1.6 on 2023-02-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='telephonesBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=15)),
                ('img_full', models.ImageField(upload_to='telephones/full/%Y/%m/%d/')),
                ('img_contraction', models.ImageField(upload_to='telephones/contraction/%Y/%m/%d/')),
            ],
        ),
    ]
