# Generated by Django 4.1.6 on 2023-02-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=15)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('img_full', models.ImageField(upload_to='telephones/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webstore.category')),
            ],
            options={
                'verbose_name': 'All product',
                'ordering': ['title', 'id'],
            },
        ),
    ]
